### PR TITLE
Seed database with historical data

### PR DESCRIPTION
**Pull request by kendajani**
- Added historical data JSON file
- Updated Prisma schema
      1. Added display name to User
      2. Added title to Course
      3. Removed meetingTime id from CourseSection
      4. Added courseSection id to MeetingTime
      5. Added Unique tags to a few of the model's combined fields
- Added some utility functions to be used in seeding
- Added seeding function

### CODE REVIEW

**Comment by LacroixJ** [comment]
'npm run build' fails, and some other issues in github actions. 

Please merge main into your branch and fix issues.

**Comment by LacroixJ** [comment]
Tested on my machine and it works.

I noticed you only added courses and not a term schedule, is that something you can do as well? We need each endpoint to return some structure so that frontend has something to work with.

**Review by LacroixJ — COMMENTED** [review]
Tested on my machine and it works.

I noticed you only added courses and not a term schedule, is that something you can do as well? We need each endpoint to return some structure so that frontend has something to work with.

**Comment by kendajani** [comment]
> Tested on my machine and it works.
> 
> I noticed you only added courses and not a term schedule, is that something you can do as well? We need each endpoint to return some structure so that frontend has something to work with.

Is that not just the course sections tho? They have the scheduled time within the meeting time object

**Comment by LacroixJ** [comment]
I tried to query for a list of all schedules in prisma and got nothing back. 

`prisma.schedule.findMany();` returns `[]`. Is that intended?

Looking at the schema, it's probably a really small fix, just assign a year and creation date to the schedule you added and it should work out. Unless you don't think we will need this table anymore, in that case it could be removed.

**Comment by kendajani** [comment]
I just assumed that the schedule would be generated using the course section info instead of it being included in the seeding? I'm honestly not sure what exactly the schedule model is

**Review by LacroixJ — APPROVED** [review]

**Pull request merged**
