### PR TITLE
Schema implementation

### PR DESCRIPTION
**Pull request by kendajani**
Added the Prisma schema implementation based on the ER diagram described in the /db folder.
Also added the migration files that initialises the PostgreSQL database.

### CODE REVIEW

**Comment by kendajani** [comment]
Ignore the revert, I forgot how to git.

**Review by aqeelmozumder — APPROVED** [review]
Looks Great

**Review by aqeelmozumder — CHANGES_REQUESTED** [review]
Comma missing in line 44 for package.json

**Review by aqeelmozumder — APPROVED** [review]
Great

**Pull request merged**
